# Generated by Django 2.2.5 on 2020-01-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20191202_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='images/ava', verbose_name='Фото'),
        ),
    ]
