# Generated by Django 2.2.5 on 2019-09-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default=1, upload_to=None),
            preserve_default=False,
        ),
    ]
