# Generated by Django 2.2.5 on 2019-09-20 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_image',
        ),
    ]
