# Generated by Django 2.2.5 on 2019-11-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_article_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Стаття', 'verbose_name_plural': 'Статті'},
        ),
        migrations.AlterModelOptions(
            name='coment',
            options={'verbose_name': 'Коментарій', 'verbose_name_plural': 'Коментарі'},
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='Admin', max_length=50, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
    ]
