# Generated by Django 2.2.5 on 2020-01-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20191109_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='link_button',
            field=models.TextField(null=True, verbose_name='Ссилка для переходу'),
        ),
    ]
