# Generated by Django 2.2.5 on 2019-12-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_event', models.TextField(max_length=200, verbose_name='Назва івенту')),
                ('event_article', models.TextField(verbose_name='Опис івенту')),
                ('event_img', models.ImageField(blank=True, null=True, upload_to='images/events/', verbose_name='Картинка івенту')),
                ('date_post', models.DateField(verbose_name='Дата створення посту')),
                ('date_do', models.DateField(verbose_name='Дата початку івенту')),
            ],
            options={
                'verbose_name': 'Івент',
                'verbose_name_plural': 'Івенти',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_member', models.TextField(max_length=200, verbose_name='Імя учасника')),
                ('contact', models.TextField(max_length=200, verbose_name='Контакти учасника')),
                ('born_date', models.TextField(max_length=200, verbose_name='Дата народження')),
            ],
            options={
                'verbose_name': 'Учасник',
                'verbose_name_plural': 'Учасники',
            },
        ),
    ]
